### ISSUE TITLE
Release new version of gem?

### ISSUE THREAD

**Issue by kaoboy7** [prontolabs/pronto#395] opened 2021-01-19 17:09 UTC
Can we release a new version of the gem? One that includes support for Thor > 1.0. Thanks!

**Comment by Kuchick** [comment] 2021-01-20 20:37
@kaoboy7 @apiology @texpert
If you upgrade Rails to 6.1 and have dependency conflict with thor, try to fetch gem not via rubygems but via github repo
For some reason 0.10.0 gem version hosted in rubygems has dependency `'thor', '~> 0.20.0'` which differs from hosted in github (`'>= 0.20.3', '< 2.0'`)
Hope that it will be helpful for you

@ashkulz @aergonaut @doomspork @mmozuras
Could you please publish the correct gem codebase to RubyGems?
Thank you!

**Comment by ashkulz** [comment] 2021-01-21 06:58
Duplicate of #376

**Closed by ashkulz** 2021-01-21 06:58 UTC

**Comment by ashkulz** [comment] 2021-01-31 05:06
A new version has been pushed to RubyGems.
