### ISSUE TITLE
Does unstaged work?

### ISSUE THREAD

**Issue by tleish** [prontolabs/pronto#243] opened 2017-06-04 14:26 UTC
Either the `--unstaged` flag does not work, or I am misunderstanding it's purpose.

I've been trying with both `--staged` and `--unstaged` flags.  Pronto is correctly picking up changes in git which are staged, but not yet committed.  

I assume `--unstaged` should pick up changes that have not yet been staged into git.  This would include updates to existing files and new files?

Also, is there a way to pick up both `--staged` and `--unstaged`?  Is it possible to pass both flags?

**Comment by mmozuras** [comment] 2017-06-04 20:14
Closing as a duplicate of #240.

Please reopen if what you'll find in #240 does not match your issue 🙂.

**Closed by mmozuras** 2017-06-04 20:14 UTC
Labels: duplicate

**Comment by tleish** [comment] 2017-06-05 13:41
Agreed.  I did search before creating ticket, the title of the ticket threw me off as I wasn't having crashing issues so I assumed it wasn't related and therefore didn't read the details.

Thanks
