### ISSUE TITLE
Upgrade rugged dependency for Ruby 3.2.0 - Dir.exists? is deprecated

### ISSUE THREAD

**Issue by arianf** [prontolabs/pronto#437] opened 2022-11-02 16:35 UTC
Can't install pronto on Ruby `3.2.0-preview2`, looks like pronto uses: `rugged  >= 0.23.0, < 1.1.0`.

Rugged 1.1.0 is using `Dir.exists?`, `Dir.exists?` is removed from Ruby 3.2

Looks like rugged 1.3.1 switches to `Dir.exist?`, see https://github.com/libgit2/rugged/commit/40be15df285c84c9c5b638698dab2f8a30330ff4

```consoole
$ gem install pronto --no-doc
Building native extensions. This could take a while...
ERROR:  Error installing pronto:
	ERROR: Failed to build gem native extension.

    current directory: /Users/arian/.rvm/gems/ruby-3.2.0-preview2/gems/rugged-1.0.1/ext/rugged
/Users/arian/.rvm/rubies/ruby-3.2.0-preview2/bin/ruby -I /Users/arian/.rvm/rubies/ruby-3.2.0-preview2/lib/ruby/3.2.0+2 extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/arian/.rvm/rubies/ruby-3.2.0-preview2/bin/$(RUBY_BASE_NAME)
	--with-sha1dc
	--without-sha1dc
	--use-system-libraries
extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
	from extconf.rb:100:in `chdir'
	from extconf.rb:100:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/arian/.rvm/gems/ruby-3.2.0-preview2/extensions/arm64-darwin-22/3.2.0+2/rugged-1.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/arian/.rvm/gems/ruby-3.2.0-preview2/gems/rugged-1.0.1 for inspection.
Results logged to /Users/arian/.rvm/gems/ruby-3.2.0-preview2/extensions/arm64-darwin-22/3.2.0+2/rugged-1.0.1/gem_make.out
```

**Comment by Vasfed** [comment] 2022-11-22 22:18
Looks like this is fixed in master - https://github.com/prontolabs/pronto/commit/839c56cfea616d1d13afa0fc7fce640b2636f513

**Comment by arianf** [comment] 2022-11-30 22:21
When will a new version of the gem be published?

**Comment by Vasfed** [comment] 2022-12-28 09:27
Now with ruby 3.2 already released more people are going to need this

**Comment by ashkulz** [comment] 2022-12-30 05:39
I'll make a release over the weekend, sorry about the delay!

**Comment by ashkulz** [comment] 2022-12-31 06:41
Duplicate of #428

**Closed by ashkulz** 2022-12-31 06:41 UTC

**Comment by ashkulz** [comment] 2022-12-31 07:21
Release `0.11.1` has been pushed to RubyGems.
