### ISSUE TITLE
stream error (Zlib::StreamError)

### ISSUE THREAD

**Issue by driv3r** [prontolabs/pronto#23] opened 2014-03-04 11:32 UTC
When running pronto with github formatter it crashes after first comment. When `GITHUB_ACCESS_TOKEN` is missing, there's the same error but without comment on PR.

Installed runners as gems (i.e. not within Gemfile):
- brakeman
- flay
- rails_best_practices
- rubocop

Backtrace:

```
$ GITHUB_ACCESS_TOKEN='...' pronto run -f github
.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:350:in `initialize': stream error (Zlib::StreamError)
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:350:in `new'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:350:in `initialize'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:257:in `new'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:257:in `inflater'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1127:in `block in get'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1413:in `block (2 levels) in transport_request'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1376:in `request'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1367:in `request'
    from .rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1126:in `get'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/sawyer-0.5.3/lib/sawyer/agent.rb:94:in `call'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/octokit-2.7.1/lib/octokit/client.rb:257:in `request'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/octokit-2.7.1/lib/octokit/client.rb:129:in `get'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/octokit-2.7.1/lib/octokit/client/commit_comments.rb:25:in `commit_comments'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/pronto-0.2.4/lib/pronto/formatter/github_formatter.rb:23:in `create_comment'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/pronto-0.2.4/lib/pronto/formatter/github_formatter.rb:14:in `block in format'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/pronto-0.2.4/lib/pronto/formatter/github_formatter.rb:7:in `map'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/pronto-0.2.4/lib/pronto/formatter/github_formatter.rb:7:in `format'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/pronto-0.2.4/lib/pronto.rb:30:in `run'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/pronto-0.2.4/lib/pronto/cli.rb:42:in `run'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from .rvm/gems/ruby-2.0.0-p247@gemset/gems/pronto-0.2.4/bin/pronto:6:in `<top (required)>'
    from .rvm/gems/ruby-2.0.0-p247@gemset/bin/pronto:23:in `load'
    from .rvm/gems/ruby-2.0.0-p247@gemset/bin/pronto:23:in `<main>'
```

**Comment by doomspork** [comment] 2016-04-26 22:25
I have now run into this issue myself.  Using the `text` formatter works but as soon as I add `github_pr` to the mix, I get the `/usr/lib/ruby/2.2.0/net/http/response.rb:355:in 'initialize': stream error (Zlib::StreamError)` error.

@mmozuras what do you need to help narrow this down?

**Comment by doomspork** [comment] 2016-04-26 22:39
The issue only seems to show up when using the `github_pr` formatter.  I tried `github` and it worked perfectly.

**Comment by doomspork** [comment] 2016-05-03 21:14
I haven't had any luck overcoming this, @mmozuras do you have any suggestions?  I'd be happy to help you troubleshoot this if you've got any suggestions on where to start.

**Comment by mmozuras** [comment] 2016-05-15 19:49
@doomspork if I could reproduce the issue, I would start by editing gem sources and logging what's happening as close to the issue as possible.

It seems to fail on this line:
`@inflate = Zlib::Inflate.new(32 + Zlib::MAX_WBITS)`
What happens when you `require 'zlib'` and try running this line in `irb`?

**Comment by doomspork** [comment] 2016-05-15 19:51
@mmozuras I haven't been able to reproduce this error since I refactored the code on my consolidate messaging branch 😧

**Comment by mmozuras** [comment] 2016-10-17 08:19
Closing as no one seems to encounter this issue anymore. 

@doomspork @driv3r please re-open if you've encountered it in the last couple of months 😄

**Comment by doomspork** [comment] 2016-10-17 16:19
Sounds good @mmozuras, I haven't run into this for some time now.

**Comment by doomspork** [comment] 2017-04-18 18:06
@mmozuras I have been able to consistently reproduce this issue now.  I'm going to work through debugging it but if you have any insights I'd love to hear them!

```shell
/usr/lib/ruby/2.3.0/net/http/response.rb:356:in `initialize': stream error (Zlib::StreamError)
	from /usr/lib/ruby/2.3.0/net/http/response.rb:356:in `new'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:356:in `initialize'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:259:in `new'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:259:in `inflater'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:281:in `read_body_0'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:202:in `read_body'
	from /usr/lib/ruby/2.3.0/net/http.rb:1157:in `block in get'
	from /usr/lib/ruby/2.3.0/net/http.rb:1446:in `block in transport_request'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:163:in `reading_body'
	from /usr/lib/ruby/2.3.0/net/http.rb:1445:in `transport_request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1156:in `get'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/response.rb:8:in `call'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/response.rb:8:in `call'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/response/logger.rb:26:in `call'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/connection.rb:386:in `run_request'
	from /var/lib/gems/2.3.0/gems/faraday-0.12.0.1/lib/faraday/connection.rb:149:in `get'
	from /var/lib/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /var/lib/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
	from /var/lib/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/connection.rb:84:in `paginate'
	from /var/lib/gems/2.3.0/gems/octokit-4.7.0/lib/octokit/client/pull_requests.rb:21:in `pull_requests'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/github.rb:105:in `pull_requests'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/github.rb:96:in `pull'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/github.rb:82:in `pull_id'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/github.rb:20:in `pull_comments'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/formatter/pull_request_formatter.rb:6:in `existing_comments'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/formatter/git_formatter.rb:6:in `format'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto.rb:59:in `block in run'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto.rb:58:in `each'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto.rb:58:in `run'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/cli.rb:54:in `block in run'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/cli.rb:53:in `chdir'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/lib/pronto/cli.rb:53:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /var/lib/gems/2.3.0/gems/pronto-0.8.2/bin/pronto:6:in `<top (required)>'
	from /var/lib/gems/2.3.0/bin/pronto:23:in `load'
	from /var/lib/gems/2.3.0/bin/pronto:23:in `<main>'
```

**Comment by mmozuras** [comment] 2017-04-19 20:34
@doomspork do you have a repo/branch/commit, which can be used to reproduce this issue? Is it reproducible on different machines?

**Comment by doomspork** [comment] 2017-04-19 20:43
@mmozuras I'm using Pronto master at the moment.  I tried scaling up the AWS box to see if it was a resource constraint to no avail, I'm going to bump it up even further and see.

I'm going to investigate this further later this week.  I'll report back my findings to you 😀

**Comment by bsedat** [comment] 2017-07-07 17:44
I think I've tracked this down to be coming from the `rugged` gem.
In a new irb console I can run:
```ruby
require 'rugged'
require 'zlib'
Zlib::Inflate.new(32 + Zlib::MAX_WBITS)
```
and produce the error consistently. Interestingly, swapping the ordering of the requires seems to fix it.

I'm running it in following environment from an alpine linux 3.6 docker container:
`ruby -v`: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-musl]`
`gem list | grep rugged`: `rugged (0.26.0)`.

**Comment by mmozuras** [comment] 2017-07-15 15:42
@bsedat I see that you're using this workaround:

https://github.com/bsedat/pronto/commit/2079aaef8dd88f3a8faf45fd7124ec7166e6a8ff

Could you explain why it works? Trying to figure out if it's worth including in `master`. Are there any possible negative side effects?

**Comment by bsedat** [comment] 2017-07-17 18:24
I unfortunately haven't had time to investigate what exactly is breaking - I didn't see any obvious culprits in rugged in a cursory glance but I'm not super familiar with that library. I don't think there are any negative side-effects from my workaround, but I'm hoping it's something that can be fixed upstream in rugged one day.

**Comment by mikkame** [comment] 2017-08-24 13:38
I get same error.

I tried pach bsedat : /pronto@2079aae .
It is worked.

My environment is  https://hub.docker.com/r/mikkame/docker-pronto-phpcs/
Maybe you can reproduce

**Comment by mmozuras** [comment] 2018-07-28 09:47
I assume that this issue is no longer valid (due to changes in newer versions). To anyone who reads this - please re-open if you encounter this issue 🙂.

**Closed by mmozuras** 2018-07-28 09:47 UTC
Labels: bug
